return {
	-- Bags
	BAG_SLOT_DEFAULT = 255,
	BAG_INVENTORY_SLOT_1 = 19,
	BAG_INVENTORY_SLOT_2 = 20,
	BAG_INVENTORY_SLOT_3 = 21,
	BAG_INVENTORY_SLOT_4 = 22,
	BAG_INVENTORY_SLOT_OFFSET = 18,

	BAG_BANK_SLOT_1 = 67,
	BAG_BANK_SLOT_2 = 68,
	BAG_BANK_SLOT_3 = 69,
	BAG_BANK_SLOT_4 = 70,
	BAG_BANK_SLOT_5 = 71,
	BAG_BANK_SLOT_6 = 72,
	BAG_BANK_SLOT_7 = 73,
	BAG_BANK_SLOT_8 = 74,

	-- Equipment
	EQUIPMENT_SLOT_HEAD = 0,
	EQUIPMENT_SLOT_NECK = 1,
	EQUIPMENT_SLOT_SHOULDERS = 2,
	EQUIPMENT_SLOT_BODY = 3,
	EQUIPMENT_SLOT_CHEST = 4,
	EQUIPMENT_SLOT_WAIST = 5,
	EQUIPMENT_SLOT_LEGS = 6,
	EQUIPMENT_SLOT_FEET = 7,
	EQUIPMENT_SLOT_WRISTS = 8,
	EQUIPMENT_SLOT_HANDS = 9,
	EQUIPMENT_SLOT_FINGER1 = 10,
	EQUIPMENT_SLOT_FINGER2 = 11,
	EQUIPMENT_SLOT_TRINKET1 = 12,
	EQUIPMENT_SLOT_TRINKET2 = 13,
	EQUIPMENT_SLOT_BACK = 14,
	EQUIPMENT_SLOT_MAINHAND = 15,
	EQUIPMENT_SLOT_OFFHAND = 16,
	EQUIPMENT_SLOT_RANGED = 17,
	EQUIPMENT_SLOT_TABARD = 18,

	-- Main bag
	MAIN_BAG_SLOT_START = 23,
	MAIN_BAG_SLOT_END = 38,

	-- Bank
	BANK_BAG_SLOT_START = 39,
	BANK_BAG_SLOT_END = 66,

	-- Keyring
	KEYRING_SLOT_START = 86,
	KEYRING_SLOT_END = 117
}
